ENV: prod
BASE_URL: 'https://www.cosmosid.com'
BASE_API_URL: 'https://app.cosmosid.com/api'
LOGIN_PAGE: 'https://app.cosmosid.com/login'
BROWSER: chrome
SUPPORTED_BROWSERS:
  - chrome
  - firefox
  - edge
  - opera